version: '3'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - "5000:5000"
    volumes:
      - ./checkpoints:/app/checkpoints
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./checkpoints:/app/checkpoints
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
