# General Configuration
general:
  seed: 42
  device: 'cuda'  # 'cuda' or 'cpu'
  num_workers: 4
  save_dir: './checkpoints'
  log_dir: './logs'
  
# Data Configuration
data:
  train_path: './data/train'
  val_path: './data/val'
  test_path: './data/test'
  frame_size: [256, 256]  # Height, Width
  sequence_length: 7  # Number of frames to process at once
  augmentation: True
  
# Training Configuration
train:
  batch_size: 8
  num_epochs: 300
  learning_rate: 0.0001
  weight_decay: 0.0001
  scheduler: 'cosine'  # 'cosine', 'step', 'plateau'
  lr_patience: 10  # For 'plateau' scheduler
  lr_step_size: 50  # For 'step' scheduler
  lr_gamma: 0.5  # For 'step' scheduler
  
# Model Configuration
model:
  type: 'vrt'  # 'vrt', 'edvr', 'restormer'
  
  # VRT Configuration
  vrt:
    embed_dim: 96
    depths: [8, 8, 8, 8]
    num_heads: [6, 6, 6, 6]
    window_size: [8, 8, 8, 8]
    mlp_ratio: 2.0
    qkv_bias: True
    qk_scale: None
    drop_rate: 0.0
    attn_drop_rate: 0.0
    drop_path_rate: 0.1
    
  # EDVR Configuration
  edvr:
    num_feat: 128
    num_frame: 7
    deformable_groups: 8
    num_extract_block: 5
    num_reconstruct_block: 10
    
  # Restormer Configuration
  restormer:
    inp_channels: 3
    out_channels: 3
    dim: 48
    num_blocks: [4, 6, 6, 8]
    num_refinement_blocks: 4
    heads: [1, 2, 4, 8]
    ffn_expansion_factor: 2.66
    bias: False
    LayerNorm_type: 'WithBias'
    
# Loss Configuration
loss:
  l1_weight: 1.0
  perceptual_weight: 0.1  # VGG perceptual loss
  adversarial_weight: 0.01  # GAN loss
  
# Evaluation Configuration
eval:
  metrics: ['psnr', 'ssim', 'lpips']
  save_results: True
  
# Inference Configuration
inference:
  checkpoint_path: './checkpoints/best_model.pth'
  input_path: './data/test_videos'
  output_path: './data/results'
  batch_size: 1
  save_frames: False  # Save individual frames
  save_video: True  # Save output video
